version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: js/install_dependencies
      timeout: 300
      runas: root
    - location: js/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: js/stop_server
      timeout: 300
      runas: root
